name: Expo CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  FIREBASE_API_KEY: AIzaSyCC3B4zjw5sprUBVnHjZYU0t-RP_1hqVcs
  FIREBASE_AUTH_DOMAIN: fitness-challenge-app-c1faa.firebaseapp.com
  FIREBASE_PROJECT_ID: fitness-challenge-app-c1faa
  FIREBASE_STORAGE_BUCKET: fitness-challenge-app-c1faa.appspot.com
  FIREBASE_MESSAGING_SENDER_ID: 214784667166
  FIREBASE_APP_ID: 1:214784667166:web:40f106b6fa8ed06c2d080f
  FIREBASE_DATABASE_URL: https://fitness-challenge-app-c1faa-default-rtdb.firebaseio.com
  FIREBASE_MEASUREMENT_ID: G-F93XTSLDBK 

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
              node-version: 14.x
          - name: Cache Node Modules
            uses: actions/cache@v2
            env:
              cache-name: cache-node-modules
            with:
              # npm cache files are stored in `~/.npm` on Linux/macOS
              path: ~/.npm
              key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-   
                ${{ runner.os }}-build- 
                ${{ runner.os }}-
          - name: Install Packages
            run: npm install
          - name: Check Lint
            run: npm run lint
          - name: Test
            run: npm run test -- --coverage
            
  expo_publish:
    name: Expo Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Packages
        run: npm install
      - name: Expo Publish
        run: expo publish

   
